### ISSUE TITLE
Add documentation for roll data on summoned actors

### ISSUE THREAD

**Issue by 9ryex5** [arbron/fvtt-summoner#3]
I'm trying to set up Summon Beast spell which increases attack damage based on the spell level, but this doesn't seem to work.
![image](https://user-images.githubusercontent.com/43207603/188293002-5c9d03c4-a3b8-4f0e-871d-17708cd2ed0f.png)

**Comment by arbron** [comment]
You cannot modify `system.bonuses.All-Damage` through the summons configuration because it is a DAE property, not core dnd5e. You can do that using the value `@summoner.item.level` in an Active Effect on the summoned creature:

![Active Effect](https://user-images.githubusercontent.com/19979839/188299519-03d5cafb-e70a-49ab-8d22-6c2f72219fe8.jpg)

I'll make a note to improve the documentation for that additional roll data to make this usage clear.

**Comment by 9ryex5** [comment]
Oh thank you, will do!
