### ISSUE TITLE
[BUG] Summon from Compendium

### ISSUE THREAD

**Issue by ZeroXNoxus** [arbron/fvtt-summoner#41]
**Describe the bug**
Summoning from a Compendium is not possible.  There is a console log, reading: 
Cannot read properties of null (reading 'clone') | summons-actor.mjs:111

**To Reproduce**
1. Add an Actor from a Compendium to a spell as summon
2. Cast spell from Spellcasting Character
3. Choose that summon and cast the spell

**Expected behavior**
Summoning from a Compendium should be possible to keep Actor Directory clean.

**Environment:**
 - Foundry Core Version: [v11.315]
 - Module Version [1.1.4]
 - Host: [e.g. self hosted]
 - OS & Browser [Windows 11, Chrome (current)]

**Additional context**

**Comment by maxobremer** [comment]
This is an issue with warpgate as mentioned in #11 and this issue is a copy of #15 (though maybe stuff has changed since then, I don't know)

Though maybe a possibility would be to have the module check if the linked actor is from a compendium
-If it is, check a folder named Arbron's Summon (or with any other prespecified name)
--if that folder doesn't have an actor there with the same name, import the actor there and summon the imported actor
--if it does have an actor with the same name, summon that one

Just a thought though, up to Arbron or whoever has time and skill to fix this.
